GET http://localhost:3001/api/notes
Content-Type: application/json

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Postman is a good tool",
  "important": true
}

###
GET http://localhost:3001/api/notes/66543135bf0bcf69694725fd


